version: '3'

services:
  auth-app:
    container_name: auth-app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - auth-db

  auth-db:
    container_name: auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: app 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
