version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  ws:
    build:
      context: .
    container_name: ws
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app
    ports:
      - "8080:8080"