[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "time", "uuid"] }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
serde = { version = "1" }
app = { path = "../app" }
