version: '3.8'

services:
  app-db:
    container_name: app-db
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGPORT: 5433
    ports:
      - "5433:5433"
    networks:
      - development
  
  app:
    container_name: app
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - development
    depends_on:
      - app-db

networks:
  development:
    driver: bridge